---

- name: Установка ClickHouse
  hosts: clickhouse
  become: true
  handlers:
    - name: Запустить сервис clickhouse-server
      ansible.builtin.service:
        name: clickhouse-server
        state: started
        enabled: true

  tasks:
    - name: Скачивание DEB-пакета ClickHouse
      ansible.builtin.get_url:
        url: "https://packages.clickhouse.com/deb/pool/main/c/{{ item }}/{{ item }}_{{ clickhouse_version }}_amd64.deb"
        dest: "/tmp/{{ item }}-{{ clickhouse_version }}_amd64.deb"
        mode: '0644'
      loop: "{{ clickhouse_packages }}"

    - name: Обновление кэша пакетов APT
      ansible.builtin.apt:
        update_cache: true

    - name: Установка пакетов Clickhouse
      ansible.builtin.apt:
        deb: "/tmp/{{ item }}-{{ clickhouse_version }}_amd64.deb"
        lock_timeout: 30
      loop: "{{ clickhouse_packages }}"
      notify: Запустить сервис clickhouse-server

    - name: Принудительный запуск сервиса
      ansible.builtin.meta: flush_handlers

    - name: Ожидание готовности clickhouse-server
      ansible.builtin.wait_for:
        host: localhost
        port: 9000
        delay: 10
        timeout: 300

    - name: Создание базы данных 'logs'
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0
  tags: clickhouse

- name: Установка Vector
  hosts: vector
  become: true
  handlers:
    - name: Запустить сервис vector
      ansible.builtin.service:
        name: vector
        state: started
        enabled: true
    - name: Перезапустить сервис vector
      ansible.builtin.service:
        name: vector
        state: restarted

  tasks:
    - name: Скачивание DEB-пакета Vector
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
        dest: "/tmp/vector-{{ vector_version }}.deb"
        mode: '0644'

    - name: Обновление кэша пакетов APT
      ansible.builtin.apt:
        update_cache: true

    - name: Установка пакета Vector
      ansible.builtin.apt:
        deb: "/tmp/vector-{{ vector_version }}.deb"
        lock_timeout: 30
      notify: Запустить сервис vector

    - name: Развёртывание конфигурационного файла Vector из шаблона
      ansible.builtin.template:
        src: vector.yaml.j2
        dest: "{{ vector_config_path }}"
        mode: '0644'
      notify: Перезапустить сервис vector

    - name: Принудительный запуск сервиса
      ansible.builtin.meta: flush_handlers
  tags: vector

- name: Установка LightHouse
  hosts: lighthouse
  become: true
  handlers:
    - name: Запустить сервис nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
    - name: Перезапустить сервис nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

  pre_tasks:
    - name: Обновление кэша пакетов APT
      ansible.builtin.apt:
        update_cache: true

    - name: Установка Git
      ansible.builtin.apt:
        name: git
        state: present
      tags: git

    - name: Установка Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
      notify: Запустить сервис nginx
      tags: nginx

  tasks:
    - name: Клонирование репозитория VKCOM/lighthouse
      ansible.builtin.git:
        repo: "{{ lighthouse_repo }}"
        version: "{{ lighthouse_version }}"
        dest: "{{ lighthouse_dir }}"

    - name: Настройка конфигурации Nginx для LightHouse
      ansible.builtin.template:
        src: lighthouse_nginx.conf.j2
        dest: /etc/nginx/sites-available/default
        mode: '0644'
      notify: Перезапустить сервис nginx

    - name: Принудительный запуск сервиса
      ansible.builtin.meta: flush_handlers
  tags: lighthouse

...
