---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-viewer
  namespace: default   # роль действует только в этом namespace
rules:
  - apiGroups: [""]      # core API группа (для pods и logs)
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch

...
