Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_check_update = true
  config.vbguest.auto_update = true

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = false
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
  end

  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -qq
    apt-get full-upgrade -y -qq
    apt-get install -y -qq build-essential dkms linux-headers-$(uname -r)
    apt-get install -y -qq python3 python3-pip
    apt-get autoremove -y -qq
    apt-get purge ~c -y -qq
  SHELL
  
  config.vm.provision "reload", type: "reload"
  
  # Master-node
  config.vm.define "master-node" do |master|
    master.vm.hostname = "master-node"
    master.vm.network "private_network", ip: "192.168.56.10"

    master.vm.provider "virtualbox" do |vb|
      vb.name = "master-node"
      vb.memory = 4096
      vb.cpus = 2
    end
  end

  # Worker-node
  $workers = 4

  (1..$workers).each do |i|
    config.vm.define "worker-node-#{i}" do |worker|
      worker.vm.hostname = "worker-node-#{i}"
      worker.vm.network "private_network", ip: "192.168.56.#{10 + i}"

      worker.vm.provider "virtualbox" do |vb|
        vb.name = "worker-node-#{i}"
        vb.memory = 2048
        vb.cpus = 1
      end
    end
  end
end