# docker build -f Dockerfile_centos -t centos-ansible:latest .

FROM centos:centos7

RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* && \
    yum groupinstall -y "Development Tools" && \
    yum install -y openssl-devel bzip2-devel libffi-devel zlib-devel wget && \
    yum clean all

RUN cd /usr/src && \
    wget https://www.python.org/ftp/python/3.8.17/Python-3.8.17.tgz && \
    tar xzf Python-3.8.17.tgz && \
    cd Python-3.8.17 && \
    ./configure --enable-optimizations && \
    make altinstall && \
    ln -sf /usr/local/bin/python3.8 /usr/bin/python3 && \
    ln -sf /usr/local/bin/python3.8 /usr/bin/python && \
    rm /usr/src/Python-3.8.17.tgz

CMD ["tail", "-f", "/dev/null"]
