# docker build -f Dockerfile_ubuntu_ansible -t ubuntu_ansible:latest .

# docker run -d --name ubuntu_ansible --privileged --cgroupns=host --stop-signal=SIGRTMIN+3 -v /sys/fs/cgroup:/sys/fs/cgroup:rw ubuntu_ansible:latest

# docker exec -it ubuntu_ansible bash

FROM ubuntu:24.04

ENV container=docker \
    DEBIAN_FRONTEND=noninteractive

RUN INSTALL_PKGS='findutils iproute2 python3 python3-apt sudo systemd' \
    && apt-get update && apt-get install $INSTALL_PKGS -y --no-install-recommends \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN find /etc/systemd/system \
    /lib/systemd/system \
    -path '*.wants/*' \
    -not -name '*journald*' \
    -not -name '*systemd-tmpfiles*' \
    -not -name '*systemd-user-sessions*' \
    -print0 | xargs -0 rm -vf   

VOLUME [ "/sys/fs/cgroup" ]

ENTRYPOINT [ "/lib/systemd/systemd" ]