# docker build -f Dockerfile_oraclelinux_ansible -t oraclelinux_ansible:latest .

# docker run -d --name oraclelinux_ansible --privileged --cgroupns=host --stop-signal=SIGRTMIN+3 -v /sys/fs/cgroup:/sys/fs/cgroup:rw oraclelinux_ansible:latest

# docker exec -it oraclelinux_ansible bash

FROM oraclelinux:8

ENV container=docker

RUN INSTALL_PKGS='findutils iproute python3 python3-dnf sudo systemd' \
    && dnf install -y --setopt=install_weak_deps=False $INSTALL_PKGS \
    && dnf clean all \
    && rm -rf /var/cache/dnf

RUN find /etc/systemd/system \
    /lib/systemd/system \
    -path '*.wants/*' \
    -not -name '*journald*' \
    -not -name '*systemd-tmpfiles*' \
    -not -name '*systemd-user-sessions*' \
    -print0 | xargs -0 rm -vf

VOLUME [ "/sys/fs/cgroup" ]

ENTRYPOINT [ "/lib/systemd/systemd" ]