---

clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 93.77.182.125
      ansible_python_interpreter: /usr/bin/python3
vector:
  hosts:
    vector-01:
      ansible_host: 89.169.143.112
      ansible_python_interpreter: /usr/bin/python3
lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 111.88.243.80
      ansible_python_interpreter: /usr/bin/python3
      
...