---

galaxy_info:
  author: Alexey Zayac
  description: This role install lighthouse
  company: Netology
  license: MIT

  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
      - all

  galaxy_tags:
    - lighthouse

dependencies: []

...