---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-exchange
  template:
    metadata:
      labels:
        app: data-exchange
    spec:

      volumes:
        - name: vol-shared
          hostPath:
            path: /tmp/

#      volumes:
#        - name: vol-shared
#          emptyDir: {}

      containers:
        - name: busybox
          image: busybox:latest
          command: ['sh', '-c', 'while true; do echo "test" >> /shared/success.txt; sleep 5; done']
          volumeMounts:
            - name: vol-shared
              mountPath: /shared

        - name: multitool
          image: wbitt/network-multitool:latest
          volumeMounts:
            - name: vol-shared
              mountPath: /shared

...
